auto_ecole_homepage:
    path:     /
    defaults: { _controller: AutoEcoleBundle:Default:index }
auto_ecole_login:
    path:     /login/{email}/{password}/{type}
    defaults: { _controller: AutoEcoleBundle:Default:login }
auto_ecole_voiture_all:
    path:     /voiture/getall
    defaults: { _controller: AutoEcoleBundle:Default:getAllVoiture }
auto_ecole_voiture:
    path:     /voiture/{id}
    defaults: { _controller: AutoEcoleBundle:Default:getVoiture }
auto_ecole_candidat_all:
    path:     /candidat/getall
    defaults: { _controller: AutoEcoleBundle:Default:getAllCandidat }
auto_ecole_minitor_calendar:
    path:     /monitor/calendar/{id}
    defaults: { _controller: AutoEcoleBundle:Default:getCalendarbyMonitor }
auto_ecole_minitor_getall:
    path:     /monitor/getall
    defaults: { _controller: AutoEcoleBundle:Default:getAllMonitor }
auto_ecole_minitor:
    path:     /monitor/{id}
    defaults: { _controller: AutoEcoleBundle:Default:getMonitor }
auto_ecole_entrainement_getall:
    path:     /entrainement
    defaults: { _controller: AutoEcoleBundle:Default:getAllEntrainement }
auto_ecole_entrainement_add:
    path:     /entrainement/create/{idcandidat}/{idmonitor}/{idvoiture}/{date}
    defaults: { _controller: AutoEcoleBundle:Default:createentrainement }
auto_ecole_entrainement_approuve:
    path:     /entrainement/approuver/{identrainement}
    defaults: { _controller: AutoEcoleBundle:Default:approuverentrainement }
auto_ecole_entrainement_disapprouve:
    path:     /entrainement/disapprouver/{identrainement}
    defaults: { _controller: AutoEcoleBundle:Default:disapprouverentrainement }
